[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#FF2400"
white = "#FFFAFA"
yellow = "#FDFF00"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#10100E"
foreground = "#C6C6C4"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "Vi"

[window]
dynamic_title = false
title = "Alacritty"

[font]
normal = {family="OpenMoji monospace", style="Regular"}
size=13
